/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CreateBountyRouteImport } from './routes/create-bounty'
import { Route as BountiesRouteImport } from './routes/bounties'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BountiesIndexRouteImport } from './routes/bounties.index'
import { Route as BountiesBountyIdRouteImport } from './routes/bounties.$bountyId'

const CreateBountyRoute = CreateBountyRouteImport.update({
  id: '/create-bounty',
  path: '/create-bounty',
  getParentRoute: () => rootRouteImport,
} as any)
const BountiesRoute = BountiesRouteImport.update({
  id: '/bounties',
  path: '/bounties',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BountiesIndexRoute = BountiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BountiesRoute,
} as any)
const BountiesBountyIdRoute = BountiesBountyIdRouteImport.update({
  id: '/$bountyId',
  path: '/$bountyId',
  getParentRoute: () => BountiesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bounties': typeof BountiesRouteWithChildren
  '/create-bounty': typeof CreateBountyRoute
  '/bounties/$bountyId': typeof BountiesBountyIdRoute
  '/bounties/': typeof BountiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-bounty': typeof CreateBountyRoute
  '/bounties/$bountyId': typeof BountiesBountyIdRoute
  '/bounties': typeof BountiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bounties': typeof BountiesRouteWithChildren
  '/create-bounty': typeof CreateBountyRoute
  '/bounties/$bountyId': typeof BountiesBountyIdRoute
  '/bounties/': typeof BountiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bounties'
    | '/create-bounty'
    | '/bounties/$bountyId'
    | '/bounties/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create-bounty' | '/bounties/$bountyId' | '/bounties'
  id:
    | '__root__'
    | '/'
    | '/bounties'
    | '/create-bounty'
    | '/bounties/$bountyId'
    | '/bounties/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BountiesRoute: typeof BountiesRouteWithChildren
  CreateBountyRoute: typeof CreateBountyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/create-bounty': {
      id: '/create-bounty'
      path: '/create-bounty'
      fullPath: '/create-bounty'
      preLoaderRoute: typeof CreateBountyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bounties': {
      id: '/bounties'
      path: '/bounties'
      fullPath: '/bounties'
      preLoaderRoute: typeof BountiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bounties/': {
      id: '/bounties/'
      path: '/'
      fullPath: '/bounties/'
      preLoaderRoute: typeof BountiesIndexRouteImport
      parentRoute: typeof BountiesRoute
    }
    '/bounties/$bountyId': {
      id: '/bounties/$bountyId'
      path: '/$bountyId'
      fullPath: '/bounties/$bountyId'
      preLoaderRoute: typeof BountiesBountyIdRouteImport
      parentRoute: typeof BountiesRoute
    }
  }
}

interface BountiesRouteChildren {
  BountiesBountyIdRoute: typeof BountiesBountyIdRoute
  BountiesIndexRoute: typeof BountiesIndexRoute
}

const BountiesRouteChildren: BountiesRouteChildren = {
  BountiesBountyIdRoute: BountiesBountyIdRoute,
  BountiesIndexRoute: BountiesIndexRoute,
}

const BountiesRouteWithChildren = BountiesRoute._addFileChildren(
  BountiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BountiesRoute: BountiesRouteWithChildren,
  CreateBountyRoute: CreateBountyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
